Will/rasa additions
ukpathologyinformatics/fastingEngine pull request #5
Opened 2022-10-14 16:21 UTC by whnds

2022-10-14 16:30 UTC, armstrongsam25 requested changes
Remove:
rasa/__init__.py
rasa/actions/____init____.py
rasa/actions/____pycache____/*

Read comments

2022-10-14 16:30 UTC, armstrongsam25 commented on rasa/actions/actions.py
> +# This files contains your custom actions which can be used to run
Remove these comments

2022-10-14 16:30 UTC, armstrongsam25 commented on rasa/config.yml
> +# # No configuration for policies was provided. The following default policies were used to train your model.
Remove these comments too

2022-10-14 16:30 UTC, armstrongsam25 commented on rasa/data/nlu.yml
> +    - startcal [10](time)
Does this work for other times?

2022-10-14 16:30 UTC, armstrongsam25 commented on rasa/domain.yml
> +  utter_cheer_up:
remove this

2022-10-14 16:30 UTC, armstrongsam25 commented on src/main/java/fasting/Webapi/API.java
> +
is the intent the 'text' variable?

2022-10-19 16:12 UTC, whnds commented on rasa/data/nlu.yml
> +    - startcal [10](time)
Yes, those are formatting examples to help Rasa recognize a time input

2022-10-19 16:36 UTC, armstrongsam25 requested changes

2022-10-19 16:36 UTC, armstrongsam25 commented on src/main/java/fasting/Webapi/API.java
> +                    System.out.println(intent); // intent of previous message
logger.error()

2022-10-19 16:45 UTC, closed without merging